spring.application.name=fix-obsolete-efos
db.batch.size=100
ols.batch.size=100
spring.data.mongodb.uri=mongodb://gwasdepo:xvUayKRZM1U@mongodb-hx-gwasdepopro-001:27017,mongodb-hl-gwasdepopro-002:27017/admin?replicaSet=gwasdepoprors080
#spring.data.mongodb.uri=mongodb://gwasdepo:oM5lnkhwneo@mongodb-hhvm-062.ebi.ac.uk:27017,mongodb-hxvm-063.ebi.ac.uk:27017/admin?replicaSet=gwasdepodevrs039
spring.data.mongodb.database=gwasdepo
spring.main.web-application-type=none
spring.datasource.url=jdbc:oracle:thin:@ora-spot-pro-hl.ebi.ac.uk:1531/SPOTPRO
spring.datasource.username=gwas
spring.datasource.password=gwas_prod07
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
